merge SI_CORE_DWH_SSI_ABSA.ENTITY_DRIVER_DETAILS AS S
	using (
Select
	ENTITY_DRIVER_DETAILS.*
from
	(
SELECT
		CONCAT(J1.ID,'|101|IDIT') ENTITY_DRIVER_DETAILS_ID,
		101 AS COMPANY_ID,
		ED.ENTITY_DRIVER_DETAILS_ID AS ENTITY_ID,
		J1.ID ENTITY_DRIVER_DETAILS_NUM,
		ED.ENTITY_FULL_NM DRIVER_NM,
		J2.DRIVING_LICENE_NR DRIVER_LICENSE_NUM,
		J1.DRIVING_LICENSE_TYPE DRIVER_LICENSE_TYPE_CD,
		(CASE WHEN CONCAT(J1.DRIVING_LICENSE_MONTH,'/',J1.DRIVING_LICENSE_YEAR)='/' THEN NULL ELSE CONCAT(J1.DRIVING_LICENSE_MONTH,'/',J1.DRIVING_LICENSE_YEAR) END)DRIVER_LICENSE_ISSUE_DT,
		(CASE WHEN CONCAT(J1.SUSPENSION_MONTH,'/',J1.SUSPENSION_YEAR)='/' THEN null ELSE CONCAT(J1.SUSPENSION_MONTH,'/',J1.SUSPENSION_YEAR)END)DRIVER_LICENSE_EXPIRY_DT,
		J1.DRIVING_LICENSE_COUNTRY_ID DL_ISSUE_COUNTRY_CD,
		J2.DRIVING_EXPERIENCE YEARS_DRIVING_EXPERIENCE,
		J1.SUSPENSION_MONTH,
		J1.SUSPENSION_YEAR,
		J1.DISCONTINUE_DATE DISCONTINUE_DT,
		'IDIT' AS AUD_SRC_SYS_NM,
		J1.ID AS AUD_SRC_SYS_ID,
		J1.UPDATE_VERSION AUD_SRC_SYS_UPDT_VER_ID,
		J1.UPDATE_DATE LAST_UPDATE_DATE,
		J1.UPDATE_USER LAST_UPDATE_USER,
		MST_TABLE_VAL_LIST1.MST_VAL_SI_DESC as DL_ISSUE_COUNTRY_NM,
		MST_TABLE_VAL_LIST2.MST_VAL_SI_DESC as DRIVER_LICENSE_TYPE_DESC,
		NULL AS ENTITY_DRIVER_DETAILS_CD,
        NULL AS SELF_DRIVE_IND,
        0 AS DRIVER_ENTITY_ID,
        NULL AS TCF_NUM,
        NULL AS DL_PLACE_OF_ISSUE_CD,
        NULL AS DL_PLACE_OF_ISSUE_NM,
        NULL AS DRIVER_EXPERT_LVL_CD,
        NULL AS DRIVER_EXPERT_LVL_DESC,
        NULL AS SUSPENSION_IND,
        NULL AS AUD_SRC_SYS_CD,
		 -- (select BATCH_ID  from SI_AUDIT_SSI_TEST_ABSA.JOB_DETAILS where JOB_NUM=4)  as AUD_BATCH_ID,
        --(select SUB_BATCH_ID  from SI_AUDIT_SSI_TEST_ABSA.JOB_DETAILS where JOB_NUM=4)  as AUD_SUB_BATCH_ID,
        1 as AUD_BATCH_ID,
		1 as AUD_SUB_BATCH_ID,
        0 as AUD_IU_FLAG

		 FROM
		(SELECT C1.CONTACT_ID,
		C1.DRIVING_LICENSE_MONTH,
		C1.DRIVING_LICENSE_YEAR,
		C1.SUSPENSION_MONTH,
		C1.SUSPENSION_YEAR,
		C1.DISCONTINUE_DATE,
		C1.ID,
		C1.DRIVING_LICENSE_COUNTRY_ID,
		C1.UPDATE_VERSION,
		C1.DRIVING_LICENSE_TYPE,
		C1.UPDATE_USER,
		C2.UPDATE_DATE
		FROM (select *
		FROM [SI_IDIT_ODS].CN_PERSON_DRIVING_DATA) c1
		 join
		(select  max(update_date) update_date,contact_id ,driving_license_type
		FROM [SI_IDIT_ODS].CN_PERSON_DRIVING_DATA
		where DISCONTINUE_DATE is NULl
		group by contact_id ,driving_license_type) c2
		on
		c1.contact_id=c2.contact_id and isnull(c1.driving_license_type,0) = isnull(c2.driving_license_type,0)
		where c2.update_date=c1.update_date
		)J1
		LEFT OUTER JOIN
		(SELECT
		C1.CONTACT_ID,
		C1.DRIVING_LICENE_NR,
		C1.DRIVING_EXPERIENCE,
		s.UPDATE_DATE FROM (select ID,
		DRIVER_ID CONTACT_ID,
		DRIVING_LICENE_NR,
		DRIVING_EXPERIENCE,
		UPDATE_DATE
		FROM [SI_IDIT_ODS].AS_VEHICLE_DRIVERS) c1
		INNER join
		(select max(ID) ID , c2.contact_id,c2.UPDATE_DATE  FROM [SI_IDIT_ODS].AS_VEHICLE_DRIVERS c3 join
		(select  max(update_date) update_date,DRIVER_ID contact_id
		FROM [SI_IDIT_ODS].AS_VEHICLE_DRIVERS
		group by DRIVER_ID ) c2
		on c3.DRIVER_ID= c2.contact_id
		and c3.UPDATE_DATE = c2.update_date
		group by c2.contact_id,c2.UPDATE_DATE) s
		on
		c1.id=s.ID
		where s.update_date=c1.update_date) J2
		ON J1.CONTACT_ID=J2.CONTACT_ID
		LEFT JOIN
		(SELECT
		ENTITY_ID ENTITY_DRIVER_DETAILS_ID,
		ENTITY_NUM,
		ENTITY_FULL_NM,
		COMPANY_ID,AUD_SRC_SYS_NM
		from
		[SI_CORE_DWH_SSI_ABSA].ENTITY_DETAILS) ED
		ON
		ED.ENTITY_NUM=J1.CONTACT_ID AND ED.AUD_SRC_SYS_NM = 'IDIT'
		LEFT JOIN
		[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST1 on MST_TABLE_VAL_LIST1.MST_TBL_VAL_NUM=J1.DRIVING_LICENSE_COUNTRY_ID and MST_TABLE_VAL_LIST1.MST_TBL_SI_CD=140009
		LEFT JOIN
		[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST2 on MST_TABLE_VAL_LIST2.MST_TBL_VAL_NUM=J1.DRIVING_LICENSE_TYPE and MST_TABLE_VAL_LIST2.MST_TBL_SI_CD=140014
	)ENTITY_DRIVER_DETAILS
Inner join (SELECT  DISTINCT Temp.ID FROM
			(SELECT C.ID,C.CONTACT_ID,C.DRIVING_LICENSE_TYPE
			FROM SI_IDIT_ODS.CN_PERSON_DRIVING_DATA C
			WHERE  ID IN (SELECT MAX(ID) ID FROM SI_IDIT_ODS.CN_PERSON_DRIVING_DATA WHERE DISCONTINUE_DATE IS NULL
			GROUP BY ID,CONTACT_ID,DRIVING_LICENSE_TYPE)
			AND UPDATE_DATE >  '1900-01-01'   AND   UPDATE_DATE <= getdate()

			UNION

			SELECT B.ID,B.CONTACT_ID,
B.DRIVING_LICENSE_TYPE--,
--B.LAST_UPDATE_DATE
FROM (SELECT  MAX(UPDATE_DATE) LAST_UPDATE_DATE,DRIVER_ID CONTACT_ID
FROM [SI_IDIT_ODS].AS_VEHICLE_DRIVERS
GROUP BY DRIVER_ID) A JOIN (
SELECT ID,CONTACT_ID,DRIVING_LICENSE_TYPE,UPDATE_DATE LAST_UPDATE_DATE
FROM [SI_IDIT_ODS].CN_PERSON_DRIVING_DATA
WHERE  ID IN (SELECT MAX(ID) ID FROM [SI_IDIT_ODS].CN_PERSON_DRIVING_DATA WHERE DISCONTINUE_DATE IS NULL GROUP BY CONTACT_ID,DRIVING_LICENSE_TYPE)
) B
ON A.CONTACT_ID = B.CONTACT_ID
WHERE A.LAST_UPDATE_DATE >'1900-01-01' AND  A.LAST_UPDATE_DATE <=getdate()
			)TEMP
) ENTITY_DRIVER_DETAILS_TEMP on
	ENTITY_DRIVER_DETAILS_TEMP.ID = ENTITY_DRIVER_DETAILS.ENTITY_DRIVER_DETAILS_NUM ) AS T ON
( S.ENTITY_DRIVER_DETAILS_ID = T.ENTITY_DRIVER_DETAILS_ID)
WHEN MATCHED THEN UPDATE SET
S.ENTITY_DRIVER_DETAILS_ID = T.ENTITY_DRIVER_DETAILS_ID,
S.COMPANY_ID = T.COMPANY_ID,
S.ENTITY_ID = T.ENTITY_ID,
S.ENTITY_DRIVER_DETAILS_NUM = T.ENTITY_DRIVER_DETAILS_NUM,
S.DRIVER_NM = T.DRIVER_NM,
S.DRIVER_LICENSE_NUM = T.DRIVER_LICENSE_NUM,
S.DRIVER_LICENSE_TYPE_CD = T.DRIVER_LICENSE_TYPE_CD,
S.DRIVER_LICENSE_ISSUE_DT = T.DRIVER_LICENSE_ISSUE_DT,
S.DRIVER_LICENSE_EXPIRY_DT = T.DRIVER_LICENSE_EXPIRY_DT,
S.DL_ISSUE_COUNTRY_CD = T.DL_ISSUE_COUNTRY_CD,
S.YEARS_DRIVING_EXPERIENCE = T.YEARS_DRIVING_EXPERIENCE,
S.SUSPENSION_MONTH = T.SUSPENSION_MONTH,
S.SUSPENSION_YEAR = T.SUSPENSION_YEAR,
S.DISCONTINUE_DT = T.DISCONTINUE_DT,
S.AUD_SRC_SYS_NM = T.AUD_SRC_SYS_NM,
S.AUD_SRC_SYS_ID = T.AUD_SRC_SYS_ID,
S.AUD_SRC_SYS_UPDT_VER_ID = T.AUD_SRC_SYS_UPDT_VER_ID,
S.LAST_UPDATE_DATE = T.LAST_UPDATE_DATE,
S.LAST_UPDATE_USER = T.LAST_UPDATE_USER,
S.DL_ISSUE_COUNTRY_NM=T.DL_ISSUE_COUNTRY_NM,
S.DRIVER_LICENSE_TYPE_DESC=T.DRIVER_LICENSE_TYPE_DESC,
S.ENTITY_DRIVER_DETAILS_CD=T.ENTITY_DRIVER_DETAILS_CD,
S.SELF_DRIVE_IND=T.SELF_DRIVE_IND,
S.DRIVER_ENTITY_ID=T.DRIVER_ENTITY_ID,
S.TCF_NUM=T.TCF_NUM,
S.DL_PLACE_OF_ISSUE_CD=T.DL_PLACE_OF_ISSUE_CD,
S.DL_PLACE_OF_ISSUE_NM=T.DL_PLACE_OF_ISSUE_NM,
S.DRIVER_EXPERT_LVL_CD=T.DRIVER_EXPERT_LVL_CD,
S.DRIVER_EXPERT_LVL_DESC=T.DRIVER_EXPERT_LVL_DESC,
S.SUSPENSION_IND=T.SUSPENSION_IND,
S.AUD_SRC_SYS_CD=T.AUD_SRC_SYS_CD,
S.AUD_BATCH_ID=T.AUD_BATCH_ID,
S.AUD_SUB_BATCH_ID=T.AUD_SUB_BATCH_ID,
S.AUD_IU_FLAG=1


WHEN NOT MATCHED BY TARGET THEN INSERT (
ENTITY_DRIVER_DETAILS_ID,
COMPANY_ID,
ENTITY_ID,
ENTITY_DRIVER_DETAILS_NUM,
DRIVER_NM,
DRIVER_LICENSE_NUM,
DRIVER_LICENSE_TYPE_CD,
DRIVER_LICENSE_ISSUE_DT,
DRIVER_LICENSE_EXPIRY_DT,
DL_ISSUE_COUNTRY_CD,
YEARS_DRIVING_EXPERIENCE,
SUSPENSION_MONTH,
SUSPENSION_YEAR,
DISCONTINUE_DT,
AUD_SRC_SYS_NM,
AUD_SRC_SYS_ID,
AUD_SRC_SYS_UPDT_VER_ID,
LAST_UPDATE_DATE,
LAST_UPDATE_USER,
DL_ISSUE_COUNTRY_NM,
DRIVER_LICENSE_TYPE_DESC,
ENTITY_DRIVER_DETAILS_CD,
SELF_DRIVE_IND,
DRIVER_ENTITY_ID,
TCF_NUM,
DL_PLACE_OF_ISSUE_CD,
DL_PLACE_OF_ISSUE_NM,
DRIVER_EXPERT_LVL_CD,
DRIVER_EXPERT_LVL_DESC,
SUSPENSION_IND,
AUD_SRC_SYS_CD,
AUD_BATCH_ID,
AUD_SUB_BATCH_ID,
AUD_IU_FLAG )

VALUES (
T.ENTITY_DRIVER_DETAILS_ID,
T.COMPANY_ID,
T.ENTITY_ID,
T.ENTITY_DRIVER_DETAILS_NUM,
T.DRIVER_NM,
T.DRIVER_LICENSE_NUM,
T.DRIVER_LICENSE_TYPE_CD,
T.DRIVER_LICENSE_ISSUE_DT,
T.DRIVER_LICENSE_EXPIRY_DT,
T.DL_ISSUE_COUNTRY_CD,
T.YEARS_DRIVING_EXPERIENCE,
T.SUSPENSION_MONTH,
T.SUSPENSION_YEAR,
T.DISCONTINUE_DT,
T.AUD_SRC_SYS_NM,
T.AUD_SRC_SYS_ID,
T.AUD_SRC_SYS_UPDT_VER_ID,
T.LAST_UPDATE_DATE,
T.LAST_UPDATE_USER,
T.DL_ISSUE_COUNTRY_NM,
T.DRIVER_LICENSE_TYPE_DESC,
T.ENTITY_DRIVER_DETAILS_CD,
T.SELF_DRIVE_IND,
T.DRIVER_ENTITY_ID,
T.TCF_NUM,
T.DL_PLACE_OF_ISSUE_CD,
T.DL_PLACE_OF_ISSUE_NM,
T.DRIVER_EXPERT_LVL_CD,
T.DRIVER_EXPERT_LVL_DESC,
T.SUSPENSION_IND,
T.AUD_SRC_SYS_CD,
T.AUD_BATCH_ID,
T.AUD_SUB_BATCH_ID,
T.AUD_IU_FLAG  ) ;
