merge SI_CORE_DWH_SSI_ABSA.INDIVIDUAL AS S
using        (
				Select
         INDIVIDUAL.*
           from
         (select
ED.ENTITY_ID AS INDI_ENTITY_ID,
ED.COMPANY_ID AS COMPANY_ID,
J1.CONTACT_ID AS INDI_ENTITY_NUM,
j3.NAME_PREFIX AS NAME_PREFIX,
j3.FIRST_NAME AS ENTITY_FIRST_NM,
j3.MIDDLE_NAME AS ENTITY_MIDDLE_NM,
j3.[NAME] AS ENTITY_LAST_NM,
case when J4.COMMENTS='VIP' then 'Yes' else 'No' end AS VIP_IND,
--G.ID AS GENDER_CD,
--G.DESCRIPTION AS GENDER_DESC,
j1.DATE_OF_BIRTH AS DT_OF_BIRTH,
j2.HEIGHT AS ENTITY_HEIGHT,
j2.WEIGHT AS ENTITY_WEIGHT,
j2.BMI AS BMI,
case when j2.SMOCKING_FLAG=1 then 'Yes' else 'No' end  AS SMOKER_IND,
case when j3.HEAD_OF_FAMILY=1 then 'Yes' else 'No' end AS HEAD_OF_FAMILY_IND,
j1.CHILDRENS AS NUM_OF_CHILDREN,
j1.ADULT_CHILDREN AS NUM_OF_ADULT_CHILDREN,
case when j3.RESIDENT_FLAG=1 then 'Yes' else 'No' end AS RESIDENT_FLAG,
j1.DISCONTINUE_DATE AS DISCONTINUE_DT,
j1.DATE_OF_DEATH AS DEATH_DT,
'IDIT' AS AUD_SRC_SYS_NM,
J1.CONTACT_ID AS AUD_SRC_SYS_ID,
j1.UPDATE_VERSION AS AUD_SRC_SYS_UPDT_VER_ID,
j1.UPDATE_DATE AS LAST_UPDATE_DATE,
MST_TABLE_VAL_LIST1.MST_VAL_SI_DESC as TITLE_DESC,
j1.TITLE as TITLE_CD,
MST_TABLE_VAL_LIST2.MST_VAL_SI_CD as GENDER_CD,
MST_TABLE_VAL_LIST2.MST_VAL_SI_DESC as GENDER_DESC,
j1.FAMILY_STATUS as MARITAL_STATUS_CD,
MST_TABLE_VAL_LIST3.MST_VAL_SI_DESC as MARITAL_STATUS_DESC,
j1.COUNTRY_BIRTH as COUNTRY_BIRTH_CD,
MST_TABLE_VAL_LIST4.MST_VAL_SI_DESC as COUNTRY_BIRTH_DESC,
j3.NATIONALITY_ID as NATIONALITY_CD,
MST_TABLE_VAL_LIST5.MST_VAL_SI_DESC as NATIONALITY_DESC,
j3.LANGUAGE_ID as LANGUAGE_CD,
MST_TABLE_VAL_LIST6.MST_VAL_SI_DESC as LANGUAGE_DESC,
j1.EDUCATION as EDUCATION_CD,
MST_TABLE_VAL_LIST7.MST_VAL_SI_DESC as EDUCATION_DESC,
j1.PROFESSION as OCCUPATION_CD,
MST_TABLE_VAL_LIST8.MST_VAL_SI_DESC as OCCUPATION_DESC,
NULL AS INDI_ENTITY_CD,
ED.ENTITY_EXTERNAL_ID AS INDI_ENTITY_EXTERNAL_ID,
NULL AS HNI_IND,
NULL AS AGE_PROOF_IND,
NULL AS AGE_VERIFICATION_IND,
NULL AS TOWN_OF_BIRTH,
NULL AS IDENTIFICATION_CD,
NULL AS IDENTIFICATION_DESC,
NULL AS DESIGNATION_CD,
NULL AS DESIGNATION_DESC,
NULL AS TRANS_CURRENCY_CD,
NULL AS TRANS_CURRENCY_DESC,
0 AS CURR_MTH_SALARY_HOME_CUR,
0 AS CURR_MTH_SALARY_TRAN_CUR,
0 AS RETIREMENT_AGE,
NULL AS DECEASED_IND,
NULL AS DEATH_REASON_ID,
NULL AS DEATH_REASON_DESC,
NULL AS FAMILY_DR_NAME,
case when USER_DETAILS.USER_ID is NUll then -99 else USER_DETAILS.USER_ID end as LAST_UPDATE_USER,
		 -- (select BATCH_ID  from SI_AUDIT_SSI_TEST_ABSA.JOB_DETAILS where JOB_NUM=4)  as AUD_BATCH_ID,
        --(select SUB_BATCH_ID  from SI_AUDIT_SSI_TEST_ABSA.JOB_DETAILS where JOB_NUM=4)  as AUD_SUB_BATCH_ID,
        1 as AUD_BATCH_ID,
		1 as AUD_SUB_BATCH_ID,
0 as AUD_IU_FLAG

--NULL AS AUD_SRC_SYS_CD,
--NULL AS AUD_BATCH_ID,
--NULL AS AUD_SUB_BATCH_ID,
--NULL AS AUD_IU_FLAG,

--j4.STATUS_ID
--ED.ENTITY_NUM,
--ED.ENTITY_EXTERNAL_ID
From
( SELECT * FROM [SI_IDIT_ODS].CN_PERSON ) j1
LEFT OUTER JOIN
(SELECT A.* FROM [SI_IDIT_ODS].AS_PERSON A INNER JOIN
(SELECT MAX(ID) ID ,CONTACT_ID FROM [SI_IDIT_ODS].AS_PERSON GROUP BY CONTACT_ID) B
ON A.ID=B.ID
)J2
ON j1.CONTACT_id=j2.contact_id
LEFT OUTER JOIN
(select * FROM [SI_IDIT_ODS].CN_CONTACT ) j3
ON j1.CONTACT_id=j3.ID
LEFT OUTER JOIN
(select STATUS_ID, A.CONTACT_ID,COMMENTS FROM [SI_IDIT_ODS].CN_CONTACT_STATUS A
JOIN (SELECT MAX(ID) AS ID,CONTACT_ID FROM [SI_IDIT_ODS].CN_CONTACT_STATUS GROUP BY CONTACT_ID)B
ON(A.ID=B.ID)) j4
ON j1.CONTACT_id=j4.CONTACT_id
LEFT OUTER JOIN
[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST1 on MST_TABLE_VAL_LIST1.MST_TBL_VAL_NUM=j1.TITLE and MST_TABLE_VAL_LIST1.MST_TBL_SI_CD=140028
LEFT OUTER JOIN
[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST2 on MST_TABLE_VAL_LIST2.MST_TBL_VAL_NUM=j1.GENDER and MST_TABLE_VAL_LIST2.MST_TBL_SI_CD=140019
LEFT OUTER JOIN
[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST3 on MST_TABLE_VAL_LIST3.MST_TBL_VAL_NUM=j1.FAMILY_STATUS and MST_TABLE_VAL_LIST3.MST_TBL_SI_CD=140018
LEFT OUTER JOIN
[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST4 on MST_TABLE_VAL_LIST4.MST_TBL_VAL_NUM=j1.COUNTRY_BIRTH and MST_TABLE_VAL_LIST4.MST_TBL_SI_CD=140009
LEFT OUTER JOIN
[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST5 on MST_TABLE_VAL_LIST5.MST_TBL_VAL_NUM=j3.NATIONALITY_ID and MST_TABLE_VAL_LIST5.MST_TBL_SI_CD=140009
LEFT OUTER JOIN
[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST6 on MST_TABLE_VAL_LIST6.MST_TBL_VAL_NUM=j3.LANGUAGE_ID and MST_TABLE_VAL_LIST6.MST_TBL_SI_CD=140021
LEFT OUTER JOIN
[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST7 on MST_TABLE_VAL_LIST7.MST_TBL_VAL_NUM=j1.EDUCATION and MST_TABLE_VAL_LIST7.MST_TBL_SI_CD=140015
LEFT OUTER JOIN
[SI_CORE_DWH_SSI_ABSA].MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST8 on MST_TABLE_VAL_LIST8.MST_TBL_VAL_NUM=j1.PROFESSION and MST_TABLE_VAL_LIST8.MST_TBL_SI_CD=140022
INNER JOIN
(SELECT
ENTITY_ID,
COMPANY_ID,
ENTITY_NUM,
ENTITY_EXTERNAL_ID
FROM
[SI_CORE_DWH_SSI_ABSA].ENTITY_DETAILS where AUD_SRC_SYS_NM = 'IDIT') ED
ON J1.CONTACT_ID=ED.ENTITY_NUM
LEFT OUTER JOIN
SI_CORE_DWH_SSI_ABSA.USER_DETAILS USER_DETAILS on USER_NUM=j1.UPDATE_USER) INDIVIDUAL
         Inner join
      (select DISTINCT
 CP.CONTACT_ID
FROM [SI_IDIT_ODS].AS_PERSON AP
 JOIN [SI_IDIT_ODS].CN_PERSON CP ON
 AP.CONTACT_id=CP.contact_id
-- JOIN
--  (SELECT ENTITY_NUM FROM
--	[SI_CORE_DWH_SSI_ABSA].ENTITY_DETAILS where AUD_SRC_SYS_NM = 'IDIT') ED
--	ON CP.CONTACT_ID=ED.ENTITY_NUM
WHERE AP.ID IN (SELECT MAX(ID) ID  FROM [SI_IDIT_ODS].AS_PERSON GROUP BY CONTACT_ID)
AND AP.UPDATE_DATE >  '1900-01-01'      AND AP.UPDATE_DATE <= getdate()

UNION
select DISTINCT
 CONTACT_ID
FROM [SI_IDIT_ODS].CN_PERSON CP
JOIN
  (SELECT ENTITY_NUM FROM
	[SI_CORE_DWH_SSI_ABSA].ENTITY_DETAILS where AUD_SRC_SYS_NM = 'IDIT') ED
	ON CP.CONTACT_ID=ED.ENTITY_NUM
 WHERE CP.UPDATE_DATE > '1900-01-01'
   AND CP.UPDATE_DATE<= getdate()

UNION

SELECT distinct
CP.CONTACT_ID as CONTACT_ID
	     from [SI_IDIT_ODS].CN_CONTACT CC
		 JOIN [SI_IDIT_ODS].CN_PERSON CP
		 ON CC.ID=CP.CONTACT_ID
--		 JOIN
--  (SELECT ENTITY_NUM FROM
--	[SI_CORE_DWH_SSI_ABSA].ENTITY_DETAILS where AUD_SRC_SYS_NM = 'IDIT') ED
--	ON CP.CONTACT_ID=ED.ENTITY_NUM
		 WHERE CC.UPDATE_DATE > '1900-01-01'
	   AND CC.UPDATE_DATE <= getdate()
	   )
       INDIVIDUAL_TEMP
       on
     INDIVIDUAL_TEMP.CONTACT_ID=INDIVIDUAL.AUD_SRC_SYS_ID)
AS T
ON
(
S.INDI_ENTITY_ID = T.INDI_ENTITY_ID
)
WHEN MATCHED THEN UPDATE SET S.INDI_ENTITY_ID = T.INDI_ENTITY_ID,
S.COMPANY_ID = T.COMPANY_ID,
S.INDI_ENTITY_NUM = T.INDI_ENTITY_NUM,
S.NAME_PREFIX = T.NAME_PREFIX,
S.ENTITY_FIRST_NM = T.ENTITY_FIRST_NM,
S.ENTITY_MIDDLE_NM = T.ENTITY_MIDDLE_NM,
S.ENTITY_LAST_NM = T.ENTITY_LAST_NM,
S.VIP_IND = T.VIP_IND,
S.DT_OF_BIRTH = T.DT_OF_BIRTH,
S.ENTITY_HEIGHT = T.ENTITY_HEIGHT,
S.ENTITY_WEIGHT = T.ENTITY_WEIGHT,
S.BMI = T.BMI,
S.SMOKER_IND = T.SMOKER_IND,
S.HEAD_OF_FAMILY_IND = T.HEAD_OF_FAMILY_IND,
S.NUM_OF_CHILDREN = T.NUM_OF_CHILDREN,
S.NUM_OF_ADULT_CHILDREN = T.NUM_OF_ADULT_CHILDREN,
S.RESIDENT_FLAG = T.RESIDENT_FLAG,
S.DISCONTINUE_DT = T.DISCONTINUE_DT,
S.DEATH_DT = T.DEATH_DT,
S.AUD_SRC_SYS_NM = T.AUD_SRC_SYS_NM,
S.AUD_SRC_SYS_ID = T.AUD_SRC_SYS_ID,
S.AUD_SRC_SYS_UPDT_VER_ID = T.AUD_SRC_SYS_UPDT_VER_ID,
S.LAST_UPDATE_DATE = T.LAST_UPDATE_DATE,
S.TITLE_DESC=T.TITLE_DESC,
S.TITLE_CD=T.TITLE_CD,
S.GENDER_CD=T.GENDER_CD,
S.GENDER_DESC=T.GENDER_DESC,
S.MARITAL_STATUS_CD=T.MARITAL_STATUS_CD,
S.MARITAL_STATUS_DESC=T.MARITAL_STATUS_DESC,
S.COUNTRY_BIRTH_CD=T.COUNTRY_BIRTH_CD,
S.COUNTRY_BIRTH_DESC=T.COUNTRY_BIRTH_DESC,
S.NATIONALITY_CD=T.NATIONALITY_CD,
S.NATIONALITY_DESC=T.NATIONALITY_DESC,
S.LANGUAGE_CD=T.LANGUAGE_CD,
S.LANGUAGE_DESC=T.LANGUAGE_DESC,
S.EDUCATION_CD=T.EDUCATION_CD,
S.EDUCATION_DESC=T.EDUCATION_DESC,
S.OCCUPATION_CD=T.OCCUPATION_CD,
S.OCCUPATION_DESC=T.OCCUPATION_DESC,
S.INDI_ENTITY_CD=T.INDI_ENTITY_CD,
S.INDI_ENTITY_EXTERNAL_ID=T.INDI_ENTITY_EXTERNAL_ID,
S.HNI_IND=T.HNI_IND,
S.AGE_PROOF_IND=T.AGE_PROOF_IND,
S.AGE_VERIFICATION_IND=T.AGE_VERIFICATION_IND,
S.TOWN_OF_BIRTH=T.TOWN_OF_BIRTH,
S.IDENTIFICATION_CD=T.IDENTIFICATION_CD,
S.IDENTIFICATION_DESC=T.IDENTIFICATION_DESC,
S.DESIGNATION_CD=T.DESIGNATION_CD,
S.DESIGNATION_DESC=T.DESIGNATION_DESC,
S.TRANS_CURRENCY_CD=T.TRANS_CURRENCY_CD,
S.TRANS_CURRENCY_DESC=T.TRANS_CURRENCY_DESC,
S.CURR_MTH_SALARY_HOME_CUR =T.CURR_MTH_SALARY_HOME_CUR ,
S.CURR_MTH_SALARY_TRAN_CUR=T.CURR_MTH_SALARY_TRAN_CUR,
S.RETIREMENT_AGE=T.RETIREMENT_AGE,
S.DECEASED_IND=T.DECEASED_IND,
S.DEATH_REASON_ID=T.DEATH_REASON_ID,
S.DEATH_REASON_DESC=T.DEATH_REASON_DESC,
S.FAMILY_DR_NAME=T.FAMILY_DR_NAME,
S.LAST_UPDATE_USER=T.LAST_UPDATE_USER,
S.AUD_BATCH_ID=T.AUD_BATCH_ID,
S.AUD_SUB_BATCH_ID=T.AUD_SUB_BATCH_ID,
S.AUD_IU_FLAG=1


WHEN NOT MATCHED BY TARGET THEN INSERT (  INDI_ENTITY_ID,
COMPANY_ID,
INDI_ENTITY_NUM,
NAME_PREFIX,
ENTITY_FIRST_NM,
ENTITY_MIDDLE_NM,
ENTITY_LAST_NM,
VIP_IND,
DT_OF_BIRTH,
ENTITY_HEIGHT,
ENTITY_WEIGHT,
BMI,
SMOKER_IND,
HEAD_OF_FAMILY_IND,
NUM_OF_CHILDREN,
NUM_OF_ADULT_CHILDREN,
RESIDENT_FLAG,
DISCONTINUE_DT,
DEATH_DT,
AUD_SRC_SYS_NM,
AUD_SRC_SYS_ID,
AUD_SRC_SYS_UPDT_VER_ID,
LAST_UPDATE_DATE,
TITLE_DESC,
TITLE_CD,
GENDER_CD,
GENDER_DESC,
MARITAL_STATUS_CD,
MARITAL_STATUS_DESC,
COUNTRY_BIRTH_CD,
COUNTRY_BIRTH_DESC,
NATIONALITY_CD,
NATIONALITY_DESC,
LANGUAGE_CD,
LANGUAGE_DESC,
EDUCATION_CD,
EDUCATION_DESC,
OCCUPATION_CD,
OCCUPATION_DESC,
INDI_ENTITY_CD,
INDI_ENTITY_EXTERNAL_ID,
HNI_IND,
AGE_PROOF_IND,
AGE_VERIFICATION_IND,
TOWN_OF_BIRTH,
IDENTIFICATION_CD,
IDENTIFICATION_DESC,
DESIGNATION_CD,
DESIGNATION_DESC,
TRANS_CURRENCY_CD,
TRANS_CURRENCY_DESC,
CURR_MTH_SALARY_HOME_CUR,
CURR_MTH_SALARY_TRAN_CUR,
RETIREMENT_AGE,
DECEASED_IND,
DEATH_REASON_ID,
DEATH_REASON_DESC,
FAMILY_DR_NAME,
LAST_UPDATE_USER,
AUD_BATCH_ID,
AUD_SUB_BATCH_ID,
AUD_IU_FLAG
)
VALUES ( T.INDI_ENTITY_ID,
T.COMPANY_ID,
T.INDI_ENTITY_NUM,
T.NAME_PREFIX,
T.ENTITY_FIRST_NM,
T.ENTITY_MIDDLE_NM,
T.ENTITY_LAST_NM,
T.VIP_IND,
T.DT_OF_BIRTH,
T.ENTITY_HEIGHT,
T.ENTITY_WEIGHT,
T.BMI,
T.SMOKER_IND,
T.HEAD_OF_FAMILY_IND,
T.NUM_OF_CHILDREN,
T.NUM_OF_ADULT_CHILDREN,
T.RESIDENT_FLAG,
T.DISCONTINUE_DT,
T.DEATH_DT,
T.AUD_SRC_SYS_NM,
T.AUD_SRC_SYS_ID,
T.AUD_SRC_SYS_UPDT_VER_ID,
T.LAST_UPDATE_DATE,
T.TITLE_DESC,
T.TITLE_CD,
T.GENDER_CD,
T.GENDER_DESC,
T.MARITAL_STATUS_CD,
T.MARITAL_STATUS_DESC,
T.COUNTRY_BIRTH_CD,
T.COUNTRY_BIRTH_DESC,
T.NATIONALITY_CD,
T.NATIONALITY_DESC,
T.LANGUAGE_CD,
T.LANGUAGE_DESC,
T.EDUCATION_CD,
T.EDUCATION_DESC,
T.OCCUPATION_CD,
T.OCCUPATION_DESC,
T.INDI_ENTITY_CD,
T.INDI_ENTITY_EXTERNAL_ID,
T.HNI_IND,
T.AGE_PROOF_IND,
T.AGE_VERIFICATION_IND,
T.TOWN_OF_BIRTH,
T.IDENTIFICATION_CD,
T.IDENTIFICATION_DESC,
T.DESIGNATION_CD,
T.DESIGNATION_DESC,
T.TRANS_CURRENCY_CD,
T.TRANS_CURRENCY_DESC,
T.CURR_MTH_SALARY_HOME_CUR,
T.CURR_MTH_SALARY_TRAN_CUR,
T.RETIREMENT_AGE,
T.DECEASED_IND,
T.DEATH_REASON_ID,
T.DEATH_REASON_DESC,
T.FAMILY_DR_NAME,
T.LAST_UPDATE_USER,
T.AUD_BATCH_ID,
T.AUD_SUB_BATCH_ID,
T.AUD_IU_FLAG
) ;