Select
count(1)
	FROM
		SI_IDIT_ODS.L_LITIGATION L_LITIGATION
Inner join (
	select
		TEMP.ID,
		MAX(TEMP.LAST_UPDATE_DATE) LAST_UPDATE_DATE
	from
		(
		SELECT
			ID,
			ARRIVAL_DATE,
			ENTITY_NR,
			TYPE,
			SUB_TYPE,
			STATUS,
			BEARING_TYPE_ID,
			STATE_ID,
			STATE_REASON_ID,
			LINKED_ENTITES_DESCRIPTION,
			UPDATE_VERSION ASAUD_SRC_SYS_UPDT_VER_ID,
			UPDATE_DATE AS LAST_UPDATE_DATE,
			UPDATE_USER AS LAST_UPDATE_USER
		FROM
			SI_IDIT_ODS.L_LITIGATION
		WHERE
			UPDATE_DATE > '1800-01-01 00:00:00.0'
			AND UPDATE_DATE <= '2022-10-10 13:38:00.923')TEMP
	group by
		TEMP.ID) LITIGATION_TEMP on
	L_LITIGATION.ID = LITIGATION_TEMP.ID