Select
	count(1)
	FROM
		SI_IDIT_ODS.AC_ENTRY AC_ENTRY
	INNER JOIN SI_CORE_DWH_SSI_ABSA.ACCOUNTING_ENTRY_LINE ACCOUNTING_ENTRY_LINE ON
		AC_ENTRY.TRANSACTION_ID = ACCOUNTING_ENTRY_LINE.ACCT_ENTRY_HEADER_NUM
		AND AC_ENTRY.ACCOUNT_ID = ACCOUNTING_ENTRY_LINE.ACCT_DET_NUM
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.CLAIMS_DETAILS CLAIMS_DETAILS ON
		AC_ENTRY.CLAIM_ID = CLAIMS_DETAILS.CLAIM_NUM
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.GENINS_INS_ITM_SEC_CVG GENINS_INS_ITM_SEC_CVG ON
		AC_ENTRY.COVER_ID = GENINS_INS_ITM_SEC_CVG.COVERAGE_NUM
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.CONTRACT CONTRACT ON
		AC_ENTRY.POLICY_HEADER_ID = CONTRACT.CONTRACT_NUM
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.GENINS_CON_VER_LOB_INS_ITM GENINS_CON_VER_LOB_INS_ITM ON
		AC_ENTRY.ORIGINAL_LOB_ASSET_ID = GENINS_CON_VER_LOB_INS_ITM.INSURED_ITEM_NUM
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.CONTRACT_VERSION CONTRACT_VERSION ON
		AC_ENTRY.POLICY_ID = CONTRACT_VERSION.CONTRACT_VERSION_NUM
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.ACCOUNTING_ENTRY_LINE ACCOUNTING_ENTRY_LINE1 ON
		AC_ENTRY.ORIGINAL_TRANSACTION_ID = ACCOUNTING_ENTRY_LINE1.ACCT_ENTRY_HEADER_NUM
		AND AC_ENTRY.ACCOUNT_ID = ACCOUNTING_ENTRY_LINE1.ACCT_DET_NUM
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.TRANSACTION_DETAILS TRANSACTION_DETAILS ON
		AC_ENTRY.REFERENCE_ID = TRANSACTION_DETAILS.TRANSACTION_NUM
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.TRANSACTION_HIST_LINE_DETAILS TRANSACTION_HIST_LINE_DETAILS ON
		AC_ENTRY.PAID_BY_INSTALLMENT_DETAILS_ID = TRANSACTION_HIST_LINE_DETAILS.TRANSACTION_HIST_LINE_NUM
		Inner join (
	select
		TEMP.ID,
		MAX(TEMP.LAST_UPDATE_DATE) LAST_UPDATE_DATE,
		TEMP.ACCOUNT_ID,
		TEMP.TRANSACTION_ID
	from
		(
		SELECT
			ID,
			UPDATE_DATE LAST_UPDATE_DATE,
			AE.ACCOUNT_ID,
			AE.TRANSACTION_ID
		FROM
			SI_IDIT_ODS.AC_ENTRY AE
		WHERE
			UPDATE_DATE >'?business_start_date'
			AND UPDATE_DATE <= '?business_end_date'
)TEMP
	group by
		TEMP.ID,
		TEMP.ACCOUNT_ID,
		TEMP.TRANSACTION_ID) ACCOUNTING_ENTRY_LINE_DETAILS_TEMP on
	ACCOUNTING_ENTRY_LINE_DETAILS_TEMP.ID = AC_ENTRY.ID
	AND
ACCOUNTING_ENTRY_LINE_DETAILS_TEMP.ACCOUNT_ID = ACCOUNTING_ENTRY_LINE.ACCT_DET_NUM
	AND
ACCOUNTING_ENTRY_LINE_DETAILS_TEMP.TRANSACTION_ID = ACCOUNTING_ENTRY_LINE.ACCT_ENTRY_HEADER_NUM