Insert
	into
	SI_CORE_DWH_SSI_ABSA.TRANSACTION_DETAILS_BATCH_LOAD_TEST (TRANSACTION_ID,
	TRANSACTION_NUM,
	TRANSACTION_CD,
	COMPANY_ID,
	CONTRACT_ID,
	CONTRACT_NUM,
	TRANSACTION_ENTITY_ID,
	TRANSACTION_ENTITY_NUM,
	TRANSACTION_PAID_AMOUNT_HOME_CUR,
	CLAIM_ID,
	CLAIM_NUM,
	DAMAGED_ITEM_PAYMENT_ID,
	DAMAGED_ITEM_PAYMENT_NUM,
	TRANSACTION_TYPE_CD,
	TRANSACTION_TYPE_DESC,
	TRANSACTION_STATUS_CD,
	TRANSACTION_STATUS_DESC,
	TRANSACTION_METHOD_CD,
	TRANSACTION_METHOD_DESC,
	TRANSACTION_ENTRY_DT,
	TRANSACTION_DUE_DT,
	TRANSACTION_RATE_DT,
	TRANSACTION_PAID_DT,
	TRANSACTIONAL_CURRENCY_CD,
	TRANSACTIONAL_CURRENCY_DESC,
	TRANSACTIONAL_CURRENCY_RATE,
	TRANSACTION_CHANNEL_TYPE_CD,
	TRANSACTION_CHANNEL_TYPE_DESC,
	ORIGINAL_TRANSACTION_ID,
	ORIGINAL_TRANSACTION_NUM,
	STORNO_TRANSACTION_ID,
	STORNO_TRANSACTION_NUM,
	TRANSACTION_AMOUNT_TRAN_CUR,
	TRANSACTION_AMOUNT_HOME_CUR,
	TRANSACTION_PAID_AMOUNT_TRAN_CUR,
	TRANSACTION_PENDING_AMOUNT_TRAN_CUR,
	TRANSACTION_PENDING_AMOUNT_HOME_CUR,
	TRANSACTION_REASON_CD,
	TRANSACTION_REASON_DESC,
	CONTRACT_VERSION_ID,
	CONTRACT_VERSION_NUM,
	TRANSACTION_SEQ_NUM,
	REMARKS,
	DOCUMENT_REFERENCE_NO,
	AUD_SRC_SYS_NM,
	AUD_SRC_SYS_ID,
	AUD_SRC_SYS_CD,
	AUD_SRC_SYS_UPDT_VER_ID,
	AUD_BATCH_ID,
	AUD_SUB_BATCH_ID,
	AUD_IU_FLAG,
	LAST_UPDATE_DATE,
	LAST_UPDATE_USER,
	CLOSING_IND,
	GROUP_INVIOCE_ID,
	GROUP_PAYROLL_RECON_ID,
	PAYER_ENTITY_ID,
	PAYER_ENTITY_NUM,
	PAYMENT_OPTION_CD,
	PAYMENT_OPTION_DESC,
	REQUEST_PAYMENT_AMOUNT,
	REQUEST_PAYMENT_AMOUNT_TYPE_CD,
	REQUEST_PAYMENT_AMOUNT_TYPE_DESC,
	TRANSACTION_COLLECTION_DT,
	TRANSACTION_SUSPENSE_AMT_HOME_CURR,
	TRANSACTION_SUSPENSE_AMT_TRAN_CURR)
Select
	concat(AC_INSTALLMENT.ID, '|', '101', '|', 'IDIT') AS TRANSACTION_ID,
	AC_INSTALLMENT.ID AS TRANSACTION_NUM,
	NULL AS TRANSACTION_CD,
	101 AS COMPANY_ID,
	CONTRACT.CONTRACT_ID AS CONTRACT_ID,
	CONTRACT.CONTRACT_NUM AS CONTRACT_NUM,
	ENTITY_DETAILS.ENTITY_ID AS TRANSACTION_ENTITY_ID,
	ENTITY_DETAILS.ENTITY_NUM AS TRANSACTION_ENTITY_NUM,
	AC_ENTRY_PA1.TRANSACTION_PAID_AMOUNT_HOME_CUR AS TRANSACTION_PAID_AMOUNT_HOME_CUR,
	CLAIMS_DETAILS.CLAIM_ID AS CLAIM_ID,
	CLAIMS_DETAILS.CLAIM_NUM AS CLAIM_NUM,
	GENINS_DAMAGED_ITEM_PAYMENTS.DAMAGED_ITEM_PAYMENT_ID AS DAMAGED_ITEM_PAYMENT_ID,
	GENINS_DAMAGED_ITEM_PAYMENTS.DAMAGED_ITEM_PAYMENT_NUM AS DAMAGED_ITEM_PAYMENT_NUM,
	MST_TABLE_VAL_LIST.MST_VAL_SI_CD AS TRANSACTION_TYPE_CD,
	MST_TABLE_VAL_LIST.MST_VAL_SI_DESC AS TRANSACTION_TYPE_DESC,
	MST_TABLE_VAL_LIST2.MST_VAL_SI_CD AS TRANSACTION_STATUS_CD,
	MST_TABLE_VAL_LIST2.MST_VAL_SI_DESC AS TRANSACTION_STATUS_DESC,
	MST_TABLE_VAL_LIST3.MST_VAL_SI_CD AS TRANSACTION_METHOD_CD,
	MST_TABLE_VAL_LIST3.MST_VAL_SI_DESC AS TRANSACTION_METHOD_DESC,
	AC_INSTALLMENT.COLLECTION_DATE AS TRANSACTION_ENTRY_DT,
	AC_INSTALLMENT.DUE_DATE AS TRANSACTION_DUE_DT,
	AC_INSTALLMENT.VALUE_DATE AS TRANSACTION_RATE_DT,
	CASE
		WHEN AC_INSTALLMENT.INSTALLMENT_STATUS = 3 THEN AC_ENTRY_PA.TRANSACTION_DATE
		ELSE NULL
	END AS TRANSACTION_PAID_DT,
	MST_TABLE_VAL_LIST6.MST_VAL_SI_CD AS TRANSACTIONAL_CURRENCY_CD,
	MST_TABLE_VAL_LIST6.MST_VAL_SI_DESC AS TRANSACTIONAL_CURRENCY_DESC,
	AC_INSTALLMENT_DETAILS1.AMOUNT_RATE AS TRANSACTIONAL_CURRENCY_RATE,
	MST_TABLE_VAL_LIST4.MST_VAL_SI_CD AS TRANSACTION_CHANNEL_TYPE_CD,
	MST_TABLE_VAL_LIST4.MST_VAL_SI_DESC AS TRANSACTION_CHANNEL_TYPE_DESC,
	NULL AS ORIGINAL_TRANSACTION_ID,
	NULL AS ORIGINAL_TRANSACTION_NUM,
	NULL AS STORNO_TRANSACTION_ID,
	NULL AS STORNO_TRANSACTION_NUM,
	AC_INSTALLMENT.ESTIMATED_AMOUNT AS TRANSACTION_AMOUNT_TRAN_CUR,
	AC_INSTALLMENT.ESTIMATED_AMOUNT_SYSTEM AS TRANSACTION_AMOUNT_HOME_CUR,
	AC_ENTRY_PA1.TRANSACTION_PAID_AMOUNT_TRAN_CUR AS TRANSACTION_PAID_AMOUNT_TRAN_CUR,
	AC_ENTRY.TRANSACTION_PENDING_AMOUNT_TRAN_CUR AS TRANSACTION_PENDING_AMOUNT_TRAN_CUR,
	AC_ENTRY.TRANSACTION_PENDING_AMOUNT_HOME_CUR AS TRANSACTION_PENDING_AMOUNT_HOME_CUR,
	MST_TABLE_VAL_LIST5.MST_VAL_SI_CD AS TRANSACTION_REASON_CD,
	MST_TABLE_VAL_LIST5.MST_VAL_SI_DESC AS TRANSACTION_REASON_DESC,
	CONTRACT_VERSION.CONTRACT_VERSION_ID AS CONTRACT_VERSION_ID,
	CONTRACT_VERSION.CONTRACT_VERSION_NUM AS CONTRACT_VERSION_NUM,
	AC_INSTALLMENT.INSTALLMENT_NUMBER AS TRANSACTION_SEQ_NUM,
	AC_INSTALLMENT.MESSAGE AS REMARKS,
	AC_INSTALLMENT.INVOICE_NUMBER AS DOCUMENT_REFERENCE_NO,
	'IDIT' AS AUD_SRC_SYS_NM,
	AC_INSTALLMENT.ID AS AUD_SRC_SYS_ID,
	NULL AS AUD_SRC_SYS_CD,
	AC_INSTALLMENT.UPDATE_VERSION AS AUD_SRC_SYS_UPDT_VER_ID,
	2484 AS AUD_BATCH_ID,
	111 AS AUD_SUB_BATCH_ID,
	0 AS AUD_IU_FLAG,
	AC_INSTALLMENT.UPDATE_DATE AS LAST_UPDATE_DATE,
	USER_DETAILS.USER_ID AS LAST_UPDATE_USER,
	NULL AS CLOSING_IND,
	NULL AS GROUP_INVIOCE_ID,
	NULL AS GROUP_PAYROLL_RECON_ID,
	ENTITY_DETAILS.ENTITY_ID AS PAYER_ENTITY_ID,
	ENTITY_DETAILS.ENTITY_NUM AS PAYER_ENTITY_NUM,
	NULL AS PAYMENT_OPTION_CD,
	NULL AS PAYMENT_OPTION_DESC,
	NULL AS REQUEST_PAYMENT_AMOUNT,
	NULL AS REQUEST_PAYMENT_AMOUNT_TYPE_CD,
	NULL AS REQUEST_PAYMENT_AMOUNT_TYPE_DESC,
	NULL AS TRANSACTION_COLLECTION_DT,
	NULL AS TRANSACTION_SUSPENSE_AMT_HOME_CURR,
	NULL AS TRANSACTION_SUSPENSE_AMT_TRAN_CURR
FROM
--	SI_IDIT_ODS.AC_INSTALLMENT AC_INSTALLMENT
	(SELECT * FROM SI_IDIT_ODS.AC_INSTALLMENT order by ID
    OFFSET '?offset' ROWS FETCH NEXT '?batchSize' ROWS ONLY)AC_INSTALLMENT
LEFT JOIN SI_CORE_DWH_SSI_ABSA.CONTRACT CONTRACT ON
	AC_INSTALLMENT.POLICY_HEADER_ID = CONTRACT.CONTRACT_NUM
	AND CONTRACT.AUD_SRC_SYS_NM = 'IDIT'
LEFT JOIN SI_CORE_DWH_SSI_ABSA.ENTITY_DETAILS ENTITY_DETAILS ON
	AC_INSTALLMENT.CONTACT_ID = ENTITY_DETAILS.ENTITY_NUM
	AND ENTITY_DETAILS.AUD_SRC_SYS_NM = 'IDIT'
LEFT JOIN (
	SELECT
		SUM(ISNULL(AC_ENTRY.AMOUNT, 0)) TRANSACTION_PAID_AMOUNT_TRAN_CUR,
		SUM(ISNULL(AC_ENTRY.AMOUNT_SYSTEM, 0)) TRANSACTION_PAID_AMOUNT_HOME_CUR,
		AI.ID
	FROM
		SI_IDIT_ODS.AC_INSTALLMENT AI
	left join SI_IDIT_ODS.AC_ENTRY AC_ENTRY ON
		AC_ENTRY.PAID_BY_INSTALLMENT_ID = AI.ID
	JOIN SI_IDIT_ODS.AC_TRANSACTION AC_TRANSACTION ON
		AC_ENTRY.TRANSACTION_ID = AC_TRANSACTION.ID
	JOIN SI_IDIT_ODS.T_TRANSACTION_TYPE T_TRANSACTION_TYPE ON
		AC_TRANSACTION.TRANSACTION_TYPE = T_TRANSACTION_TYPE.ID
		AND
 ((T_TRANSACTION_TYPE.VIEW_TRANSACTION_TYPE_ID = 3
			AND T_TRANSACTION_TYPE.NOT_FOR_INSTALLMENT_BALANCE = 0)
		OR T_TRANSACTION_TYPE.IS_MARK_AS_PAID_FLAG = 1)
	GROUP BY
		AI.ID) AC_ENTRY_PA1 ON
	AC_ENTRY_PA1.ID = AC_INSTALLMENT.ID
LEFT JOIN SI_CORE_DWH_SSI_ABSA.CLAIMS_DETAILS CLAIMS_DETAILS ON
	AC_INSTALLMENT.CLAIM_ID = CLAIMS_DETAILS.CLAIM_NUM
	AND CLAIMS_DETAILS.AUD_SRC_SYS_NM = 'IDIT'
LEFT JOIN SI_CORE_DWH_SSI_ABSA.GENINS_DAMAGED_ITEM_PAYMENTS GENINS_DAMAGED_ITEM_PAYMENTS ON
	AC_INSTALLMENT.CLAIM_TRANSACTION_ID = GENINS_DAMAGED_ITEM_PAYMENTS.DAMAGED_ITEM_PAYMENT_NUM
	AND GENINS_DAMAGED_ITEM_PAYMENTS.AUD_SRC_SYS_NM = 'IDIT'
LEFT JOIN SI_CORE_DWH_SSI_ABSA.MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST ON
	AC_INSTALLMENT.INSTALLMENT_TYPE = MST_TABLE_VAL_LIST.MST_TBL_VAL_NUM
	and MST_TABLE_VAL_LIST.MST_TBL_NM_SHRT = 'MST_INSTALLMENT_TYPE'
LEFT JOIN SI_CORE_DWH_SSI_ABSA.MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST2 ON
	AC_INSTALLMENT.INSTALLMENT_STATUS = MST_TABLE_VAL_LIST2.MST_TBL_VAL_NUM
	and MST_TABLE_VAL_LIST2.MST_TBL_NM_SHRT = 'MST_INSTALLMENT_STATUS_TYPE'
LEFT JOIN SI_CORE_DWH_SSI_ABSA.MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST3 ON
	AC_INSTALLMENT.COLLECTION_METHOD_ID = MST_TABLE_VAL_LIST3.MST_TBL_VAL_NUM
	and MST_TABLE_VAL_LIST3.MST_TBL_NM_SHRT = 'MST_COLLECTION_METHOD'
LEFT JOIN (
	SELECT
		C.TRANSACTION_DATE,
		B.PAID_BY_INSTALLMENT_ID
	FROM
		(
		SELECT
			MAX(B.TRANSACTION_ID) TRANSACTION_ID,
			B.PAID_BY_INSTALLMENT_ID
		FROM
			SI_IDIT_ODS.AC_INSTALLMENT A
		INNER JOIN SI_IDIT_ODS.AC_ENTRY B ON
			A.ID = B.PAID_BY_INSTALLMENT_ID
			AND B.TRANSACTION_TYPE_ID != 10112
			AND B.AMOUNT<0
		GROUP BY
			B.PAID_BY_INSTALLMENT_ID) B
	INNER JOIN (
		SELECT
			SUM(AMOUNT) AMOUNT ,
			PAID_BY_INSTALLMENT_ID
		FROM
			SI_IDIT_ODS.AC_ENTRY
		WHERE
			TRANSACTION_TYPE_ID != 10112
		GROUP BY
			PAID_BY_INSTALLMENT_ID)D
ON
		B.PAID_BY_INSTALLMENT_ID = D.PAID_BY_INSTALLMENT_ID
		AND D.AMOUNT = 0
	INNER JOIN SI_IDIT_ODS.AC_TRANSACTION C ON
		B.TRANSACTION_ID = C.ID) AC_ENTRY_PA ON
	AC_INSTALLMENT.ID = AC_ENTRY_PA.PAID_BY_INSTALLMENT_ID
LEFT JOIN (
	SELECT
		DISTINCT AID.CURRENCY_ID,
		AID.INSTALLMENT_HISTORY_ID,
		AID.POLICY_ID
	FROM
		SI_IDIT_ODS.AC_INSTALLMENT_DETAILS AID
	JOIN SI_IDIT_ODS.T_CURRENCY T
ON
		AID.CURRENCY_ID = T.ID) AC_INSTALLMENT_DETAILS ON
	AC_INSTALLMENT.LAST_INSTALLMENT_HISTORY_ID = AC_INSTALLMENT_DETAILS.INSTALLMENT_HISTORY_ID
	and AC_INSTALLMENT.POLICY_ID = AC_INSTALLMENT_DETAILS.POLICY_ID
LEFT JOIN SI_CORE_DWH_SSI_ABSA.MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST6 ON
	AC_INSTALLMENT_DETAILS.CURRENCY_ID = MST_TABLE_VAL_LIST6.MST_TBL_VAL_NUM
	and MST_TABLE_VAL_LIST6.MST_TBL_NM_SHRT = 'MST_CURRENCY'
LEFT JOIN (
	SELECT
		INSTALLMENT_HISTORY_ID,
		AMOUNT_RATE
	FROM
		SI_IDIT_ODS.AC_INSTALLMENT_DETAILS
	WHERE
		ID IN(
		SELECT
			MAX(ID)
		FROM
			SI_IDIT_ODS.AC_INSTALLMENT_DETAILS
		GROUP BY
			INSTALLMENT_HISTORY_ID)) AC_INSTALLMENT_DETAILS1 ON
	AC_INSTALLMENT.LAST_INSTALLMENT_HISTORY_ID = AC_INSTALLMENT_DETAILS1.INSTALLMENT_HISTORY_ID
LEFT JOIN SI_CORE_DWH_SSI_ABSA.MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST4 ON
	AC_INSTALLMENT.CHANNEL_TYPE_ID = MST_TABLE_VAL_LIST4.MST_TBL_VAL_NUM
	and MST_TABLE_VAL_LIST4.MST_TBL_NM_SHRT = 'MST_CHANNEL_TYPE'
LEFT JOIN (
	SELECT
		ACC.ID,
		ACC.TAXES_AMOUNT + ISNULL(ACC1.AMOUNT,
		0) - ISNULL(ACC2.AMOUNT,
		0) TRANSACTION_PENDING_AMOUNT_TRAN_CUR,
		ACC.TAXES_AMOUNT_SYSTEM + ISNULL( ACC1.AMOUNT_SYSTEM,
		0) - ISNULL(ACC2.AMOUNT_SYSTEM,
		0) TRANSACTION_PENDING_AMOUNT_HOME_CUR
	FROM
		SI_IDIT_ODS.AC_INSTALLMENT ACC
	left JOIN
  (
		SELECT
			SUM(ISNULL(AID.AMOUNT, 0)) AMOUNT,
			SUM(ISNULL(AID.AMOUNT_SYSTEM, 0)) AMOUNT_SYSTEM,
			AC.ID
		FROM
			SI_IDIT_ODS.AC_INSTALLMENT_DETAILS AID
		JOIN SI_IDIT_ODS.AC_INSTALLMENT AC
 ON
			AID.INSTALLMENT_HISTORY_ID = AC.LAST_INSTALLMENT_HISTORY_ID
		GROUP BY
			AC.ID
 ) ACC1
 ON
		ACC.ID = ACC1.ID
	LEFT JOIN
 (
		SELECT
			SUM(ISNULL(AE.AMOUNT, 0)) AMOUNT,
			SUM(ISNULL(AE.AMOUNT_SYSTEM, 0)) AMOUNT_SYSTEM,
			AI.ID
		FROM
			SI_IDIT_ODS.AC_INSTALLMENT AI
		left join SI_IDIT_ODS.AC_ENTRY AE ON
			AE.PAID_BY_INSTALLMENT_ID = AI.ID
		JOIN SI_IDIT_ODS.AC_TRANSACTION AT
 ON
			AE.TRANSACTION_ID = AT.ID
		JOIN SI_IDIT_ODS.T_TRANSACTION_TYPE T
 ON
			AT.TRANSACTION_TYPE = T.ID
			AND ((T.VIEW_TRANSACTION_TYPE_ID = 3
				AND NOT_FOR_INSTALLMENT_BALANCE = 0)
			OR T.IS_MARK_AS_PAID_FLAG = 1)
		GROUP BY
			AI.ID
 ) ACC2
 ON
		ACC.ID = ACC2.ID
) AC_ENTRY ON
	AC_INSTALLMENT.ID = AC_ENTRY.ID
LEFT JOIN SI_CORE_DWH_SSI_ABSA.MST_TABLE_VAL_LIST MST_TABLE_VAL_LIST5 ON
	AC_INSTALLMENT.INSTALLMENT_ORIGIN_ID = MST_TABLE_VAL_LIST5.MST_TBL_VAL_NUM
	and MST_TABLE_VAL_LIST5.MST_TBL_NM_SHRT = 'MST_INSTALLMENT_ORIGIN'
LEFT JOIN SI_CORE_DWH_SSI_ABSA.CONTRACT_VERSION CONTRACT_VERSION ON
	AC_INSTALLMENT.POLICY_ID = CONTRACT_VERSION.CONTRACT_VERSION_NUM
	AND CONTRACT_VERSION.AUD_SRC_SYS_NM = 'IDIT'
LEFT JOIN SI_CORE_DWH_SSI_ABSA.USER_DETAILS USER_DETAILS ON
	AC_INSTALLMENT.UPDATE_USER = USER_DETAILS.USER_NUM