Select count (1) FROM

		SI_IDIT_ODS.AC_INSTALLMENT AC_INSTALLMENT
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.CONTRACT CONTRACT ON
		AC_INSTALLMENT.POLICY_HEADER_ID = CONTRACT.CONTRACT_NUM
		AND CONTRACT.AUD_SRC_SYS_NM = 'IDIT'
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.ENTITY_DETAILS ENTITY_DETAILS ON
		AC_INSTALLMENT.CONTACT_ID = ENTITY_DETAILS.ENTITY_NUM
		AND ENTITY_DETAILS.AUD_SRC_SYS_NM = 'IDIT'
	LEFT JOIN (
		SELECT
			SUM(ISNULL(AC_ENTRY.AMOUNT, 0)) TRANSACTION_PAID_AMOUNT_TRAN_CUR,
			SUM(ISNULL(AC_ENTRY.AMOUNT_SYSTEM, 0)) TRANSACTION_PAID_AMOUNT_HOME_CUR,
			AI.ID
		FROM
			SI_IDIT_ODS.AC_INSTALLMENT AI
		left join SI_IDIT_ODS.AC_ENTRY AC_ENTRY ON
			AC_ENTRY.PAID_BY_INSTALLMENT_ID = AI.ID
		JOIN SI_IDIT_ODS.AC_TRANSACTION AC_TRANSACTION ON
			AC_ENTRY.TRANSACTION_ID = AC_TRANSACTION.ID
		JOIN SI_IDIT_ODS.T_TRANSACTION_TYPE T_TRANSACTION_TYPE ON
			AC_TRANSACTION.TRANSACTION_TYPE = T_TRANSACTION_TYPE.ID
			AND ((T_TRANSACTION_TYPE.VIEW_TRANSACTION_TYPE_ID = 3
				AND T_TRANSACTION_TYPE.NOT_FOR_INSTALLMENT_BALANCE = 0)
			OR T_TRANSACTION_TYPE.IS_MARK_AS_PAID_FLAG = 1)
		GROUP BY
			AI.ID) AC_ENTRY_PA1 ON
		AC_ENTRY_PA1.ID = AC_INSTALLMENT.ID
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.CLAIMS_DETAILS CLAIMS_DETAILS ON
		AC_INSTALLMENT.CLAIM_ID = CLAIMS_DETAILS.CLAIM_NUM
		AND CLAIMS_DETAILS.AUD_SRC_SYS_NM = 'IDIT'
	LEFT JOIN SI_CORE_DWH_SSI_ABSA.GENINS_DAMAGED_ITEM_PAYMENTS GENINS_DAMAGED_ITEM_PAYMENTS ON
		AC_INSTALLMENT.CLAIM_TRANSACTION_ID = GENINS_DAMAGED_ITEM_PAYMENTS.DAMAGED_ITEM_PAYMENT_NUM
		AND GENINS_DAMAGED_ITEM_PAYMENTS.AUD_SRC_SYS_NM = 'IDIT'

	LEFT JOIN (
		SELECT
			C.TRANSACTION_DATE,
			B.PAID_BY_INSTALLMENT_ID
		FROM
			(
			SELECT
				MAX(B.TRANSACTION_ID) TRANSACTION_ID,
				B.PAID_BY_INSTALLMENT_ID
			FROM
				SI_IDIT_ODS.AC_INSTALLMENT A
			INNER JOIN SI_IDIT_ODS.AC_ENTRY B ON
				A.ID = B.PAID_BY_INSTALLMENT_ID
				AND B.TRANSACTION_TYPE_ID != 10112
				AND B.AMOUNT<0
			GROUP BY
				B.PAID_BY_INSTALLMENT_ID) B
		INNER JOIN (
			SELECT
				SUM(AMOUNT) AMOUNT ,
				PAID_BY_INSTALLMENT_ID
			FROM
				SI_IDIT_ODS.AC_ENTRY
			WHERE
				TRANSACTION_TYPE_ID != 10112
			GROUP BY
				PAID_BY_INSTALLMENT_ID)D ON
			B.PAID_BY_INSTALLMENT_ID = D.PAID_BY_INSTALLMENT_ID
			AND D.AMOUNT = 0
		INNER JOIN SI_IDIT_ODS.AC_TRANSACTION C ON
			B.TRANSACTION_ID = C.ID) AC_ENTRY_PA ON
		AC_INSTALLMENT.ID = AC_ENTRY_PA.PAID_BY_INSTALLMENT_ID
	LEFT JOIN (
		SELECT
			DISTINCT AID.CURRENCY_ID,
			AID.INSTALLMENT_HISTORY_ID,
			AID.POLICY_ID
		FROM
			SI_IDIT_ODS.AC_INSTALLMENT_DETAILS AID
		JOIN SI_IDIT_ODS.T_CURRENCY T ON
			AID.CURRENCY_ID = T.ID) AC_INSTALLMENT_DETAILS ON
		AC_INSTALLMENT.LAST_INSTALLMENT_HISTORY_ID = AC_INSTALLMENT_DETAILS.INSTALLMENT_HISTORY_ID
		and AC_INSTALLMENT.POLICY_ID = AC_INSTALLMENT_DETAILS.POLICY_ID

	LEFT JOIN (
		SELECT
			INSTALLMENT_HISTORY_ID,
			AMOUNT_RATE
		FROM
			SI_IDIT_ODS.AC_INSTALLMENT_DETAILS
		WHERE
			ID IN(
			SELECT
				MAX(ID)
			FROM
				SI_IDIT_ODS.AC_INSTALLMENT_DETAILS
			GROUP BY
				INSTALLMENT_HISTORY_ID)) AC_INSTALLMENT_DETAILS1 ON
		AC_INSTALLMENT.LAST_INSTALLMENT_HISTORY_ID = AC_INSTALLMENT_DETAILS1.INSTALLMENT_HISTORY_ID

	LEFT JOIN (
		SELECT
			ACC.ID,
			ACC.TAXES_AMOUNT + ISNULL(ACC1.AMOUNT,
			0) - ISNULL(ACC2.AMOUNT,
			0) TRANSACTION_PENDING_AMOUNT_TRAN_CUR,
			ACC.TAXES_AMOUNT_SYSTEM + ISNULL( ACC1.AMOUNT_SYSTEM,
			0) - ISNULL(ACC2.AMOUNT_SYSTEM,
			0) TRANSACTION_PENDING_AMOUNT_HOME_CUR
		FROM
			SI_IDIT_ODS.AC_INSTALLMENT ACC
		left JOIN (
			SELECT
				SUM(ISNULL(AID.AMOUNT, 0)) AMOUNT,
				SUM(ISNULL(AID.AMOUNT_SYSTEM, 0)) AMOUNT_SYSTEM,
				AC.ID
			FROM
				SI_IDIT_ODS.AC_INSTALLMENT_DETAILS AID
			JOIN SI_IDIT_ODS.AC_INSTALLMENT AC ON
				AID.INSTALLMENT_HISTORY_ID = AC.LAST_INSTALLMENT_HISTORY_ID
			GROUP BY
				AC.ID ) ACC1 ON
			ACC.ID = ACC1.ID
		LEFT JOIN (
			SELECT
				SUM(ISNULL(AE.AMOUNT, 0)) AMOUNT,
				SUM(ISNULL(AE.AMOUNT_SYSTEM, 0)) AMOUNT_SYSTEM,
				AI.ID
			FROM
				SI_IDIT_ODS.AC_INSTALLMENT AI
			left join SI_IDIT_ODS.AC_ENTRY AE ON
				AE.PAID_BY_INSTALLMENT_ID = AI.ID
			JOIN SI_IDIT_ODS.AC_TRANSACTION AT ON
				AE.TRANSACTION_ID = AT.ID
			JOIN SI_IDIT_ODS.T_TRANSACTION_TYPE T ON
				AT.TRANSACTION_TYPE = T.ID
				AND ((T.VIEW_TRANSACTION_TYPE_ID = 3
					AND NOT_FOR_INSTALLMENT_BALANCE = 0)
				OR T.IS_MARK_AS_PAID_FLAG = 1)
			GROUP BY
				AI.ID ) ACC2 ON
			ACC.ID = ACC2.ID ) AC_ENTRY ON
		AC_INSTALLMENT.ID = AC_ENTRY.ID

	LEFT JOIN SI_CORE_DWH_SSI_ABSA.CONTRACT_VERSION CONTRACT_VERSION ON
		AC_INSTALLMENT.POLICY_ID = CONTRACT_VERSION.CONTRACT_VERSION_NUM
		AND CONTRACT_VERSION.AUD_SRC_SYS_NM = 'IDIT'
Inner join (
	SELECT
		ID,
		UPDATE_DATE AS LAST_UPDATE_DATE
	FROM
		SI_IDIT_ODS.AC_INSTALLMENT
	WHERE
		UPDATE_DATE>'1800-01-01 00:00:00.0'
		AND UPDATE_DATE <= '2022-10-17 07:47:20.999'
		) TRANSACTION_DETAILS_TEMP on
	TRANSACTION_DETAILS_TEMP.ID = AC_INSTALLMENT.ID